import { environmentCommonDev } from "./environment.common-dev";
export const environment = {
  production: false,
  environmentName: "century-dev",
  API_URL: "http://dev.loyalie.in/winnre/",
  CONTEXT_PATH: "century-admin/",
  CLIENT_ID: "73a80a393c511787ed36c7e96e90d8f7780eb7e32a4aeecadddd292028aa33bb",
  TITLE: "Century Circle",
  LOGO: "assets/images/century_logo_final.png",
  SIDE_BAR_LOGO: "assets/images_new/logo/century.jpg",
  LOADER: "assets/images/century_logo.png",
  PRIMARY_COLOR: "#64412b",
  SECONDARY_COLOR: "#f7f7f7",
  LOGIN_BG: "#e6c168",
  BUTTON_COLOR: "#e6c168",
  conectreClient: true,
  showManageCustomers: true,
  enableCustomCollateral: false,
  enableMRP: true,
  enableAboutUS: true,
  enableBrokerageCalculator: false,
  showManageCPs: false,
  enableSMConfig: true,
  PROJECT_NAME: "century",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonDev,
};
