import { environmentCommonProd } from "./environment.common-prod";
export const environment = {
  production: true,
  environmentName: "prod",
  API_URL: "https://prod.loyalie.in/winnre/",
  CONTEXT_PATH: "winnre-admin/",
  CLIENT_ID: "43f9ae0bd0e04f52e4d95b93bcf34138dbf6052b78dc2710ff4eb90b3c69f096",
  TITLE: "Happiedge",
  LOGO: "assets/images/home.png",
  SIDE_BAR_LOGO: "assets/images/admin.png",
  LOADER: "assets/images/BrigadeLogoTransparentBG100x100pxl.gif",
  PRIMARY_COLOR: "#e6e4e4",
  SECONDARY_COLOR: "#231f20",
  LOGIN_BG: "#024c9e",
  BUTTON_COLOR: "#f7941e",
  conectreClient: false,
  showManageCustomers: false,
  enableCustomCollateral: true,
  enableMRP: true,
  enableAboutUS: true,
  enableBrokerageCalculator: true,
  showManageCPs: false,
  enableSMConfig: true,
  PROJECT_NAME: "happiedge",
  COMMON_FILES: environmentCommonProd,
};
