export const environment = {
  production: true,
  environmentName: "vapt",
  API_URL: "https://happiedge-uat.mahindrahappinest.com/happiedge/",
  TITLE: "Happiedge",
  LOGO: "assets/images/home.png",
  SIDE_BAR_LOGO: "assets/images/admin.png",
  LOADER: "assets/images/BrigadeLogoTransparentBG100x100pxl.gif",
  PRIMARY_COLOR: "#e6e4e4",
  SECONDARY_COLOR: "#231f20",
  LOGIN_BG: "#024c9e",
  BUTTON_COLOR: "#f7941e",
  conectreClient: false,
  showManageCustomers: false,
  enableCustomCollateral: true,
  enableMRP: true,
  enableAboutUS: true,
  enableBrokerageCalculator: false,
  showManageCPs: false,
  enableSMConfig: true,
  PROJECT_NAME: "happiedge",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
};
