import { environmentCommonUat } from "./environment.common-uat";
export const environment = {
  production: true,
  environmentName: "godrej-uat",
  API_URL: "https://uat.loyalie.in/winnre/",
  CONTEXT_PATH: "godrej-admin/",
  CLIENT_ID: "4757d92ecbc85bd93320870e1d15ae79788920c0cbf41abe884bfbc4980a0c08",
  TITLE: "Godrej",
  LOGO: "assets/images/godrej_logo_final.png",
  SIDE_BAR_LOGO: "assets/images_new/logo/godrej.jpg",
  LOADER: "assets/images/godrejLogo.png",
  PRIMARY_COLOR: "#64412b",
  SECONDARY_COLOR: "#f7f7f7",
  LOGIN_BG: "#F58020",
  BUTTON_COLOR: "#373737",
  conectreClient: false,
  showManageCustomers: true,
  enableCustomCollateral: true,
  enableMRP: true,
  enableAboutUS: true,
  enableBrokerageCalculator: false,
  showManageCPs: true,
  enableSMConfig: true,
  PROJECT_NAME: "godrej",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonUat,
};
