import { environmentCommonDev } from "./environment.common-dev";

export const environment = {
  production: false,
  environmentName: "dev",
  API_URL: "http://dev.loyalie.in/winnre/",
  CONTEXT_PATH: "winnre-admin/",
  CLIENT_ID: "43f9ae0bd0e04f52e4d95b93bcf34138dbf6052b78dc2710ff4eb90b3c69f096",
  TITLE: "Reloy",
  LOGO: "assets/images/reloyimg.png",
  SIDE_BAR_LOGO: "assets/images_new/logo/reloy-v.svg",
  LOADER: "assets/images/defaultLoading.gif",
  PRIMARY_COLOR: "#e6e4e4",
  SECONDARY_COLOR: "#231f20",
  LOGIN_BG: "#024c9e",
  BUTTON_COLOR: "#f7941e",
  conectreClient: false,
  showManageCustomers: true,
  enableCustomCollateral: true,
  enableMRP: true,
  enableAboutUS: true,
  enableBrokerageCalculator: true,
  showManageCPs: true,
  enableSMConfig: true,
  PROJECT_NAME: "happiedge",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonDev,
};
