import { environmentCommonDev } from "./environment.common-dev";
export const environment = {
  production: false,
  environmentName: "arvind-dev",
  API_URL: "http://dev.loyalie.in/winnre/",
  CONTEXT_PATH: "arvind-admin/",
  CLIENT_ID: "48999a82ce0a3ea0a08e23b5e495b8bd6b8e8189e99bdd6563bd9700cada9b2a",
  TITLE: "Arvind",
  LOGO: "assets/images_new/logo/arvind_logo.png",
  SIDE_BAR_LOGO: "assets/images_new/logo/arvind_logo.png",
  LOADER: "assets/images_new/logo/arvind_loader.gif",
  PRIMARY_COLOR: "#9F1C3D",
  SECONDARY_COLOR: "#000000",
  LOGIN_BG: "#FFFFFF",
  BUTTON_COLOR: "#000000",
  conectreClient: true,
  showManageCustomers: false,
  enableMRP: false,
  enableAboutUS: true,
  enableCustomCollateral: false,
  enableBrokerageCalculator: false,
  enableSMConfig: false,
  showManageCPs: false,
  PROJECT_NAME: "arvind",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonDev,
};
