import { environmentCommonDev } from "./environment.common-dev";
export const environment = {
  production: false,
  environmentName: "srijan-dev",
  API_URL: "http://dev.loyalie.in/winnre/",
  CONTEXT_PATH: "srijan-admin/",
  CLIENT_ID: "f44e78c8b0cd6357b7393b2ed2f77998e41aba2db0a1f424561b1e67ada29884",
  TITLE: "Srijan",
  LOGO: "assets/images/srijan_logo_final.png",
  SIDE_BAR_LOGO: "assets/images_new/logo/White-logo-Srijan_Connect.png",
  LOADER: "assets/images/srijan_logo.gif",
  PRIMARY_COLOR: "#e6e4e4",
  SECONDARY_COLOR: "#231f20",
  LOGIN_BG: "#15519E",
  BUTTON_COLOR: "#15519e",
  conectreClient: true,
  showManageCustomers: true,
  enableCustomCollateral: false,
  enableMRP: true,
  enableAboutUS: true,
  enableBrokerageCalculator: false,
  showManageCPs: false,
  enableSMConfig: true,
  PROJECT_NAME: "srijan",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonDev,
};
