import { environmentCommonProd } from "./environment.common-prod";

export const environment = {
  production: true,
  environmentName: "embassy-prod",
  API_URL: "https://prod.loyalie.in/winnre/",
  CONTEXT_PATH: "embassy-admin/",
  CLIENT_ID: "576105b5b11f0894b219ccfbadece57ae637db4513eaee8c1c12436438925fed",
  TITLE: "Embassy",
  LOGO: "assets/images_new/logo/embassy-priority-logo.png",
  SIDE_BAR_LOGO: "assets/images_new/logo/embassy-priority-logo.jpg",
  LOADER: "assets/images_new/logo/embassy-loader.gif",
  PRIMARY_COLOR: "#f7941d",
  SECONDARY_COLOR: "#faa74a",
  LOGIN_BG: "#58595b",
  BUTTON_COLOR: "#58595b",
  conectreClient: true,
  showManageCustomers: true,
  enableCustomCollateral: false,
  enableMRP: true,
  enableAboutUS: true,
  enableBrokerageCalculator: false,
  showManageCPs: false,
  enableSMConfig: true,
  PROJECT_NAME: "embassy",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonProd,
};
