import { environmentCommonDev } from "./environment.common-dev";
export const environment = {
  production: false,
  environmentName: "dev",
  API_URL: "http://dev.loyalie.in/winnre/",
  CONTEXT_PATH: "mahindra-admin/",
  CLIENT_ID: "89f7c75cc7d56d4969a90431f3aa0bf6dff0f21e8656455ae0068483f578584a",
  TITLE: "Happiedge",
  LOGO: "assets/images/happiedge_logo_final.png",
  SIDE_BAR_LOGO: "assets/images_new/logo/Mahindra.jpg",
  LOADER: "assets/images/mahindra.gif",
  PRIMARY_COLOR: "#e6e4e4",
  SECONDARY_COLOR: "#231f20",
  LOGIN_BG: "#024c9e",
  BUTTON_COLOR: "#f7941e",
  conectreClient: false,
  showManageCustomers: false,
  enableCustomCollateral: true,
  enableMRP: true,
  enableAboutUS: true,
  enableBrokerageCalculator: false,
  showManageCPs: true,
  enableSMConfig: true,
  PROJECT_NAME: "happiedge",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonDev,
};
