import { environmentCommonProd } from "./environment.common-prod";

export const environment = {
  production: true,
  environmentName: "brigade-prod",
  API_URL: "https://partnerplus.brigadegroup.com/winnre/",
  CONTEXT_PATH: "brigade-admin/",
  CLIENT_ID: "d89dd1904c633eefaf744ddae973353fb23dac86e2438ede72dd60a3345301c8",
  TITLE: "Brigade",
  LOGO: "assets/images/brigade_logo_final.png",
  SIDE_BAR_LOGO: "assets/images_new/logo/Brigade_new.jpg",
  LOADER: "assets/images/brigade_loader1.gif",
  PRIMARY_COLOR: "#e6e4e4",
  SECONDARY_COLOR: "#231f20",
  LOGIN_BG: "#024c9e",
  BUTTON_COLOR: "#f7941e",
  conectreClient: false,
  showManageCustomers: false,
  enableCustomCollateral: true,
  enableMRP: false,
  enableAboutUS: false,
  enableBrokerageCalculator: false,
  showManageCPs: true,
  enableSMConfig: false,
  PROJECT_NAME: "brigade",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonProd,
};
