import { environmentCommonUat } from "./environment.common-uat";
export const environment = {
  production: false,
  environmentName: "spre-uat",
  API_URL: "https://uat.loyalie.in/winnre/",
  CONTEXT_PATH: "spre-admin/",
  CLIENT_ID: "b170c980898c1639711e4613010044c8bfa37f205d1c599e54660417645e9c8b",
  TITLE: "SPRE",
  LOGO: "assets/images/spre_logo_final.jpg",
  SIDE_BAR_LOGO: "assets/images_new/logo/SPRE.jpg",
  LOADER: "assets/images/affinity-new.gif",
  PRIMARY_COLOR: "#e6e4e4",
  SECONDARY_COLOR: "#231f20",
  LOGIN_BG: "#000000",
  BUTTON_COLOR: "#D4AF37",
  conectreClient: false,
  showManageCustomers: false,
  enableCustomCollateral: true,
  enableMRP: true,
  enableAboutUS: false,
  enableBrokerageCalculator: false,
  showManageCPs: true,
  enableSMConfig: true,
  PROJECT_NAME: "spre",
  loginMainText: "Manage Your Channel Partners",
  loginSubText: "Leads | Brokerage | Notifications",
  COMMON_FILES: environmentCommonUat,
};
